spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/my_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  mapper-locations: mapper/*.xml